### PR TITLE
Updated Semi 2013

### PR DESCRIPTION
**Pull request by ky-1**
**This is the biggest update yet.** It adds: liking, disliking, subscribing and more. The watch page has been improved and more css has been added. Additionally an early (non functional) version of the inbox featureh as been added. Names been changed from Revista to Catrill too if you didn't know (with permission from woozie as long as I give credit).
The `skeuo` branch is now deprecated and it has none of these major changes. All feature updates will be to the `semi-2013` branch.

### CODE REVIEW

**Comment by jkosixtyfour** [comment]
True...

**Comment by ky-1** [comment]
also fixed some issues (eg i made the guide be hidden on screens smaller than 1030px wide so the page doesn't get fucked up

**Comment by bluer0ck** [comment]
very cool.....

**Comment by ky-1** [comment]
for real brother

**Comment by ky-1** [comment]
see its good!!!
image

**Comment by ky-1** [comment]
ok now im done

**Comment by jkosixtyfour** [comment]
ready ???

**Comment by ky-1** [comment]
YEs

**Comment by ky-1** [comment]
YAY!!

**Comment by ky-1** [comment]
image

**Pull request merged**
